import EffectSemantics.Denotational.TypedShallow

namespace EffectSemantics

/-- Downward-closed languages of possible ordered traces. -/
structure EffectLanguage where
  contains : Effect → Prop
  downward : ∀ {smaller larger}, smaller ≤ larger → contains larger →
    contains smaller

namespace EffectLanguage

theorem ext {left right : EffectLanguage}
    (containsEq : left.contains = right.contains) : left = right := by
  cases left with
  | mk leftContains leftDownward =>
      cases right with
      | mk rightContains rightDownward =>
          cases containsEq
          rfl

def Le (left right : EffectLanguage) : Prop :=
  ∀ effect, left.contains effect → right.contains effect

instance : LE EffectLanguage := ⟨Le⟩

theorem le_refl (language : EffectLanguage) : language ≤ language :=
  fun _ member => member

theorem le_trans {left middle right : EffectLanguage}
    (first : left ≤ middle) (second : middle ≤ right) : left ≤ right :=
  fun effect member => second effect (first effect member)

/-- Principal language generated by one may-effect upper word. -/
def principal (upper : Effect) : EffectLanguage where
  contains trace := trace ≤ upper
  downward := by
    intro smaller larger below member
    exact Effect.le_trans below member

theorem principal_mono (bound : lower ≤ upper) :
    principal lower ≤ principal upper := by
  change ∀ effect, effect ≤ lower → effect ≤ upper
  exact fun _ member => Effect.le_trans member bound

/-- Sequential product of trace languages. -/
def seq (left right : EffectLanguage) : EffectLanguage where
  contains trace := ∃ leftTrace rightTrace,
    left.contains leftTrace ∧ right.contains rightTrace ∧
      trace ≤ leftTrace * rightTrace
  downward := by
    intro smaller larger below
    rintro ⟨leftTrace, rightTrace, leftMember, rightMember, largerBound⟩
    exact ⟨leftTrace, rightTrace, leftMember, rightMember,
      Effect.le_trans below largerBound⟩

/-- Monotone language-level shallow transformer: transform each possible
trace, then take downward closure. -/
def handle (selected : Nat) (replacement : Effect)
    (language : EffectLanguage) : EffectLanguage where
  contains output := ∃ input, language.contains input ∧
    output ≤ TypedWriterTree.replaceFirst selected replacement input
  downward := by
    intro smaller larger below
    rintro ⟨input, inputMember, largerBound⟩
    exact ⟨input, inputMember, Effect.le_trans below largerBound⟩

theorem handle_mono (bound : lower ≤ upper) :
    handle selected replacement lower ≤ handle selected replacement upper := by
  change ∀ output,
    (∃ input, lower.contains input ∧
      output ≤ TypedWriterTree.replaceFirst selected replacement input) →
    ∃ input, upper.contains input ∧
      output ≤ TypedWriterTree.replaceFirst selected replacement input
  change (∀ effect, lower.contains effect → upper.contains effect) at bound
  rintro output ⟨input, inputMember, outputBound⟩
  exact ⟨input, bound input inputMember, outputBound⟩

theorem replaced_mem_handle_principal (input : Effect) :
    (handle selected replacement (principal input)).contains
      (TypedWriterTree.replaceFirst selected replacement input) :=
  by
    change ∃ source, source ≤ input ∧
      TypedWriterTree.replaceFirst selected replacement input ≤
        TypedWriterTree.replaceFirst selected replacement source
    exact ⟨input, Effect.le_refl input,
      Effect.le_refl (TypedWriterTree.replaceFirst selected replacement input)⟩

/-- The finite word envelope from the counterexample analysis bounds the whole
handled principal language. -/
theorem handle_principal_le_envelope :
    handle selected replacement (principal upper) ≤
      principal (TypedWriterTree.replacementEnvelope selected replacement upper) := by
  change ∀ output,
    (∃ input, input ≤ upper ∧
      output ≤ TypedWriterTree.replaceFirst selected replacement input) →
    output ≤ TypedWriterTree.replacementEnvelope selected replacement upper
  rintro output ⟨input, inputBound, outputBound⟩
  exact Effect.le_trans outputBound
    (TypedWriterTree.replaceFirst_le_envelope inputBound)

theorem seq_mono (leftBound : left ≤ left') (rightBound : right ≤ right') :
    seq left right ≤ seq left' right' := by
  change (∀ effect, left.contains effect → left'.contains effect) at leftBound
  change (∀ effect, right.contains effect → right'.contains effect) at rightBound
  change ∀ trace,
    (∃ leftTrace rightTrace, left.contains leftTrace ∧
      right.contains rightTrace ∧ trace ≤ leftTrace * rightTrace) →
    ∃ leftTrace rightTrace, left'.contains leftTrace ∧
      right'.contains rightTrace ∧ trace ≤ leftTrace * rightTrace
  rintro trace ⟨leftTrace, rightTrace, leftMember, rightMember, traceBound⟩
  exact ⟨leftTrace, rightTrace, leftBound _ leftMember,
    rightBound _ rightMember, traceBound⟩

theorem principal_seq (left right : Effect) :
    seq (principal left) (principal right) = principal (left * right) := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  constructor
  · rintro ⟨leftTrace, rightTrace, leftBound, rightBound, traceBound⟩
    exact Effect.le_trans traceBound (Effect.le_seq leftBound rightBound)
  · intro traceBound
    exact ⟨left, right, Effect.le_refl left, Effect.le_refl right, traceBound⟩

/-- Downward closure of all finite repetitions of one ordered atom.  This is
the smallest simple iteration grade needed by `op; self()`. -/
def repeatAtom (atom : EffectAtom) : EffectLanguage where
  contains trace := ∃ count, trace ≤ List.replicate count atom
  downward := by
    intro smaller larger below
    rintro ⟨count, bound⟩
    exact ⟨count, Effect.le_trans below bound⟩

theorem pure_mem_repeatAtom (atom : EffectAtom) :
    (repeatAtom atom).contains 1 := by
  exact ⟨0, Effect.le_refl 1⟩

/-- Unlike a finite word, the iteration language absorbs one mandatory
occurrence on the left. -/
theorem principal_atom_seq_repeatAtom_le (atom : EffectAtom) :
    seq (principal [atom]) (repeatAtom atom) ≤ repeatAtom atom := by
  rintro trace ⟨leftTrace, rightTrace, leftBound,
    ⟨count, rightBound⟩, traceBound⟩
  refine ⟨count + 1, ?_⟩
  apply Effect.le_trans traceBound
  apply Effect.le_trans (Effect.le_seq leftBound rightBound)
  simpa [List.replicate_succ, List.append_assoc] using
    Effect.le_refl ([atom] * List.replicate count atom)

theorem seq_assoc (first second third : EffectLanguage) :
    seq (seq first second) third = seq first (seq second third) := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  constructor
  · rintro ⟨firstSecond, thirdTrace,
      ⟨firstTrace, secondTrace, firstMember, secondMember, firstSecondBound⟩,
      thirdMember, traceBound⟩
    refine ⟨firstTrace, secondTrace * thirdTrace, firstMember,
      ⟨secondTrace, thirdTrace, secondMember, thirdMember, Effect.le_refl _⟩, ?_⟩
    apply Effect.le_trans traceBound
    apply Effect.le_trans
      (Effect.le_seq firstSecondBound (Effect.le_refl thirdTrace))
    simpa only [Effect.mul_assoc] using
      Effect.le_refl (firstTrace * (secondTrace * thirdTrace))
  · rintro ⟨firstTrace, secondThird, firstMember,
      ⟨secondTrace, thirdTrace, secondMember, thirdMember, secondThirdBound⟩,
      traceBound⟩
    refine ⟨firstTrace * secondTrace, thirdTrace,
      ⟨firstTrace, secondTrace, firstMember, secondMember, Effect.le_refl _⟩,
      thirdMember, ?_⟩
    apply Effect.le_trans traceBound
    apply Effect.le_trans
      (Effect.le_seq (Effect.le_refl firstTrace) secondThirdBound)
    simpa only [Effect.mul_assoc] using
      Effect.le_refl ((firstTrace * secondTrace) * thirdTrace)

theorem seq_one_left (language : EffectLanguage) :
    seq (principal 1) language = language := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  constructor
  · rintro ⟨pureTrace, rightTrace, pureBound, rightMember, traceBound⟩
    have pureEq := Effect.sublist_nil pureBound
    subst pureTrace
    exact language.downward (by simpa using traceBound) rightMember
  · intro member
    exact ⟨1, trace, Effect.le_refl 1, member, by
      simpa using Effect.le_refl trace⟩

theorem seq_one_right (language : EffectLanguage) :
    seq language (principal 1) = language := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  constructor
  · rintro ⟨leftTrace, pureTrace, leftMember, pureBound, traceBound⟩
    have pureEq := Effect.sublist_nil pureBound
    subst pureTrace
    exact language.downward (by simpa using traceBound) leftMember
  · intro member
    exact ⟨trace, 1, member, Effect.le_refl 1, by
      simpa using Effect.le_refl trace⟩

end EffectLanguage
end EffectSemantics
