import EffectSemantics.Denotational.TypedShallow

namespace EffectSemantics

/-- Downward-closed languages of possible ordered traces. -/
structure EffectLanguage where
  contains : Effect → Prop
  downward : ∀ {smaller larger}, smaller ≤ larger → contains larger →
    contains smaller

namespace EffectLanguage

theorem ext {left right : EffectLanguage}
    (containsEq : left.contains = right.contains) : left = right := by
  cases left with
  | mk leftContains leftDownward =>
      cases right with
      | mk rightContains rightDownward =>
          cases containsEq
          rfl

def Le (left right : EffectLanguage) : Prop :=
  ∀ effect, left.contains effect → right.contains effect

instance : LE EffectLanguage := ⟨Le⟩

theorem le_refl (language : EffectLanguage) : language ≤ language :=
  fun _ member => member

theorem le_trans {left middle right : EffectLanguage}
    (first : left ≤ middle) (second : middle ≤ right) : left ≤ right :=
  fun effect member => second effect (first effect member)

theorem le_antisymm {left right : EffectLanguage}
    (forward : left ≤ right) (backward : right ≤ left) : left = right := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  exact ⟨forward trace, backward trace⟩

/-- Empty downward-closed language. -/
def bottom : EffectLanguage where
  contains _ := False
  downward := by intros; contradiction

theorem bottom_le (language : EffectLanguage) : bottom ≤ language := by
  intro _ member
  exact False.elim member

/-- Binary union of possible traces. -/
def join (left right : EffectLanguage) : EffectLanguage where
  contains trace := left.contains trace ∨ right.contains trace
  downward := by
    intro smaller larger below member
    cases member with
    | inl leftMember => exact Or.inl (left.downward below leftMember)
    | inr rightMember => exact Or.inr (right.downward below rightMember)

theorem le_join_left (left right : EffectLanguage) : left ≤ join left right :=
  fun _ member => Or.inl member

theorem le_join_right (left right : EffectLanguage) : right ≤ join left right :=
  fun _ member => Or.inr member

theorem join_le (leftBound : left ≤ upper) (rightBound : right ≤ upper) :
    join left right ≤ upper := by
  intro trace member
  exact member.elim (leftBound trace) (rightBound trace)

theorem join_mono (leftBound : left ≤ left') (rightBound : right ≤ right') :
    join left right ≤ join left' right' :=
  join_le (le_trans leftBound (le_join_left _ _))
    (le_trans rightBound (le_join_right _ _))

/-- Intersection of all pre-fixed points.  This construction needs no
choice of a domain library and gives the complete-lattice least fixed point
used for recursive effect equations. -/
def leastPrefixed (function : EffectLanguage → EffectLanguage) :
    EffectLanguage where
  contains trace := ∀ candidate, function candidate ≤ candidate →
    candidate.contains trace
  downward := by
    intro smaller larger below member candidate prefixed
    exact candidate.downward below (member candidate prefixed)

theorem leastPrefixed_le (prefixed : function candidate ≤ candidate) :
    leastPrefixed function ≤ candidate :=
  fun _ member => member candidate prefixed

theorem function_le_leastPrefixed
    (monotone : ∀ {left right}, left ≤ right → function left ≤ function right) :
    function (leastPrefixed function) ≤ leastPrefixed function := by
  intro trace member candidate prefixed
  exact prefixed trace
    (monotone (leastPrefixed_le prefixed) trace member)

theorem leastPrefixed_le_function
    (monotone : ∀ {left right}, left ≤ right → function left ≤ function right) :
    leastPrefixed function ≤ function (leastPrefixed function) := by
  apply leastPrefixed_le
  exact monotone (function_le_leastPrefixed monotone)

theorem leastPrefixed_fixed
    (monotone : ∀ {left right}, left ≤ right → function left ≤ function right) :
    function (leastPrefixed function) = leastPrefixed function := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  exact ⟨function_le_leastPrefixed monotone trace,
    leastPrefixed_le_function monotone trace⟩

/-- Principal language generated by one may-effect upper word. -/
def principal (upper : Effect) : EffectLanguage where
  contains trace := trace ≤ upper
  downward := by
    intro smaller larger below member
    exact Effect.le_trans below member

theorem principal_mono (bound : lower ≤ upper) :
    principal lower ≤ principal upper := by
  change ∀ effect, effect ≤ lower → effect ≤ upper
  exact fun _ member => Effect.le_trans member bound

/-- Principal-language embedding reflects the original finite-word order. -/
theorem le_of_principal_le (bound : principal lower ≤ principal upper) :
    lower ≤ upper :=
  bound lower (Effect.le_refl lower)

theorem principal_le_principal_iff :
    principal lower ≤ principal upper ↔ lower ≤ upper :=
  ⟨le_of_principal_le, principal_mono⟩

/-- Sequential product of trace languages. -/
def seq (left right : EffectLanguage) : EffectLanguage where
  contains trace := ∃ leftTrace rightTrace,
    left.contains leftTrace ∧ right.contains rightTrace ∧
      trace ≤ leftTrace * rightTrace
  downward := by
    intro smaller larger below
    rintro ⟨leftTrace, rightTrace, leftMember, rightMember, largerBound⟩
    exact ⟨leftTrace, rightTrace, leftMember, rightMember,
      Effect.le_trans below largerBound⟩

/-- Monotone language-level shallow transformer: transform each possible
trace, then take downward closure. -/
def handle (selected : Nat) (replacement : Effect)
    (language : EffectLanguage) : EffectLanguage where
  contains output := ∃ input, language.contains input ∧
    output ≤ TypedWriterTree.replaceFirst selected replacement input
  downward := by
    intro smaller larger below
    rintro ⟨input, inputMember, largerBound⟩
    exact ⟨input, inputMember, Effect.le_trans below largerBound⟩

/-- First-occurrence handling with a language-valued clause effect. -/
def handleWith (selected : Nat) (replacement input : EffectLanguage) :
    EffectLanguage where
  contains output := ∃ source, input.contains source ∧
    ((EffectAtom.free selected ∉ source ∧ output ≤ source) ∨
      ∃ replacementTrace, replacement.contains replacementTrace ∧
        output ≤ TypedWriterTree.replaceFirst selected replacementTrace source)
  downward := by
    intro smaller larger below
    rintro ⟨source, sourceMember, unchanged | replaced⟩
    · exact ⟨source, sourceMember, Or.inl
        ⟨unchanged.1, Effect.le_trans below unchanged.2⟩⟩
    · rcases replaced with ⟨replacementTrace, replacementMember, largerBound⟩
      exact ⟨source, sourceMember, Or.inr
        ⟨replacementTrace, replacementMember,
          Effect.le_trans below largerBound⟩⟩

theorem handleWith_mono
    (replacementBound : replacement ≤ replacement')
    (inputBound : input ≤ input') :
    handleWith selected replacement input ≤
      handleWith selected replacement' input' := by
  rintro output ⟨source, sourceMember, unchanged | replaced⟩
  · exact ⟨source, inputBound source sourceMember, Or.inl unchanged⟩
  · rcases replaced with ⟨replacementTrace, replacementMember, outputBound⟩
    exact ⟨source, inputBound source sourceMember, Or.inr
      ⟨replacementTrace, replacementBound replacementTrace replacementMember,
        outputBound⟩⟩

theorem pure_le_handleWith (inputPure : principal 1 ≤ input) :
    principal 1 ≤ handleWith selected replacement input := by
  intro output outputPure
  have outputNil := Effect.sublist_nil outputPure
  subst output
  exact ⟨1, inputPure 1 (Effect.le_refl 1), Or.inl
    ⟨by simp, Effect.le_refl 1⟩⟩

/-- A currently exposed selected request followed by `suffix` is transformed
to the clause language followed by that same suffix. -/
theorem seq_replacement_le_handleWith
    (inputBound : seq (principal [EffectAtom.free selected]) suffix ≤ input) :
    seq replacement suffix ≤ handleWith selected replacement input := by
  rintro output ⟨replacementTrace, suffixTrace, replacementMember,
    suffixMember, outputBound⟩
  let source := [EffectAtom.free selected] * suffixTrace
  have sourceMember : input.contains source := inputBound source
    ⟨[EffectAtom.free selected], suffixTrace, Effect.le_refl _, suffixMember,
      Effect.le_refl _⟩
  refine ⟨source, sourceMember, Or.inr
    ⟨replacementTrace, replacementMember, ?_⟩⟩
  simpa [source, TypedWriterTree.replaceFirst, Effect.mul_def] using outputBound

/-- A pure clause eliminates the only selected request in a singleton
principal input language. -/
theorem handleWith_pure_singleton (selected : Nat) :
    handleWith selected (principal 1)
      (principal [EffectAtom.free selected]) = principal 1 := by
  apply le_antisymm
  · rintro output ⟨source, sourceBound, unchanged | replaced⟩
    · cases source with
      | nil => exact unchanged.2
      | cons atom rest =>
          have atomMember : atom ∈ [EffectAtom.free selected] :=
            sourceBound.subset (by simp)
          have atomEq : atom = EffectAtom.free selected := by
            simpa using atomMember
          subst atom
          exact False.elim (unchanged.1 (by simp))
    · rcases replaced with ⟨replacementTrace, replacementPure, outputBound⟩
      have replacementEq := Effect.sublist_nil replacementPure
      subst replacementTrace
      cases source with
      | nil => exact outputBound
      | cons atom rest =>
          cases sourceBound with
          | cons _ impossible =>
              have sourceNil := List.eq_nil_of_sublist_nil impossible
              contradiction
          | cons_cons _ restBound =>
              have restNil := List.eq_nil_of_sublist_nil restBound
              subst rest
              change output ≤ (1 : Effect)
              simpa [TypedWriterTree.replaceFirst] using outputBound
  · exact pure_le_handleWith
      (principal_mono (Effect.nil_le [EffectAtom.free selected]))

theorem handle_mono (bound : lower ≤ upper) :
    handle selected replacement lower ≤ handle selected replacement upper := by
  change ∀ output,
    (∃ input, lower.contains input ∧
      output ≤ TypedWriterTree.replaceFirst selected replacement input) →
    ∃ input, upper.contains input ∧
      output ≤ TypedWriterTree.replaceFirst selected replacement input
  change (∀ effect, lower.contains effect → upper.contains effect) at bound
  rintro output ⟨input, inputMember, outputBound⟩
  exact ⟨input, bound input inputMember, outputBound⟩

theorem replaced_mem_handle_principal (input : Effect) :
    (handle selected replacement (principal input)).contains
      (TypedWriterTree.replaceFirst selected replacement input) :=
  by
    change ∃ source, source ≤ input ∧
      TypedWriterTree.replaceFirst selected replacement input ≤
        TypedWriterTree.replaceFirst selected replacement source
    exact ⟨input, Effect.le_refl input,
      Effect.le_refl (TypedWriterTree.replaceFirst selected replacement input)⟩

/-- The finite word envelope from the counterexample analysis bounds the whole
handled principal language. -/
theorem handle_principal_le_envelope :
    handle selected replacement (principal upper) ≤
      principal (TypedWriterTree.replacementEnvelope selected replacement upper) := by
  change ∀ output,
    (∃ input, input ≤ upper ∧
      output ≤ TypedWriterTree.replaceFirst selected replacement input) →
    output ≤ TypedWriterTree.replacementEnvelope selected replacement upper
  rintro output ⟨input, inputBound, outputBound⟩
  exact Effect.le_trans outputBound
    (TypedWriterTree.replaceFirst_le_envelope inputBound)

theorem seq_mono (leftBound : left ≤ left') (rightBound : right ≤ right') :
    seq left right ≤ seq left' right' := by
  change (∀ effect, left.contains effect → left'.contains effect) at leftBound
  change (∀ effect, right.contains effect → right'.contains effect) at rightBound
  change ∀ trace,
    (∃ leftTrace rightTrace, left.contains leftTrace ∧
      right.contains rightTrace ∧ trace ≤ leftTrace * rightTrace) →
    ∃ leftTrace rightTrace, left'.contains leftTrace ∧
      right'.contains rightTrace ∧ trace ≤ leftTrace * rightTrace
  rintro trace ⟨leftTrace, rightTrace, leftMember, rightMember, traceBound⟩
  exact ⟨leftTrace, rightTrace, leftBound _ leftMember,
    rightBound _ rightMember, traceBound⟩

/-- If the left computation may return purely, sequencing it before `right`
does not remove any behavior of `right`. -/
theorem le_seq_of_pure_left (pureBound : principal 1 ≤ left) :
    right ≤ seq left right := by
  intro trace member
  exact ⟨1, trace, pureBound 1 (Effect.le_refl 1), member, by
    simpa using Effect.le_refl trace⟩

theorem principal_seq (left right : Effect) :
    seq (principal left) (principal right) = principal (left * right) := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  constructor
  · rintro ⟨leftTrace, rightTrace, leftBound, rightBound, traceBound⟩
    exact Effect.le_trans traceBound (Effect.le_seq leftBound rightBound)
  · intro traceBound
    exact ⟨left, right, Effect.le_refl left, Effect.le_refl right, traceBound⟩

/-- Downward closure of all finite repetitions of one ordered atom.  This is
the smallest simple iteration grade needed by `op; self()`. -/
def repeatAtom (atom : EffectAtom) : EffectLanguage where
  contains trace := ∃ count, trace ≤ List.replicate count atom
  downward := by
    intro smaller larger below
    rintro ⟨count, bound⟩
    exact ⟨count, Effect.le_trans below bound⟩

theorem pure_mem_repeatAtom (atom : EffectAtom) :
    (repeatAtom atom).contains 1 := by
  exact ⟨0, Effect.le_refl 1⟩

/-- Unlike a finite word, the iteration language absorbs one mandatory
occurrence on the left. -/
theorem principal_atom_seq_repeatAtom_le (atom : EffectAtom) :
    seq (principal [atom]) (repeatAtom atom) ≤ repeatAtom atom := by
  rintro trace ⟨leftTrace, rightTrace, leftBound,
    ⟨count, rightBound⟩, traceBound⟩
  refine ⟨count + 1, ?_⟩
  apply Effect.le_trans traceBound
  apply Effect.le_trans (Effect.le_seq leftBound rightBound)
  simpa [List.replicate_succ, List.append_assoc] using
    Effect.le_refl ([atom] * List.replicate count atom)

theorem seq_assoc (first second third : EffectLanguage) :
    seq (seq first second) third = seq first (seq second third) := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  constructor
  · rintro ⟨firstSecond, thirdTrace,
      ⟨firstTrace, secondTrace, firstMember, secondMember, firstSecondBound⟩,
      thirdMember, traceBound⟩
    refine ⟨firstTrace, secondTrace * thirdTrace, firstMember,
      ⟨secondTrace, thirdTrace, secondMember, thirdMember, Effect.le_refl _⟩, ?_⟩
    apply Effect.le_trans traceBound
    apply Effect.le_trans
      (Effect.le_seq firstSecondBound (Effect.le_refl thirdTrace))
    simpa only [Effect.mul_assoc] using
      Effect.le_refl (firstTrace * (secondTrace * thirdTrace))
  · rintro ⟨firstTrace, secondThird, firstMember,
      ⟨secondTrace, thirdTrace, secondMember, thirdMember, secondThirdBound⟩,
      traceBound⟩
    refine ⟨firstTrace * secondTrace, thirdTrace,
      ⟨firstTrace, secondTrace, firstMember, secondMember, Effect.le_refl _⟩,
      thirdMember, ?_⟩
    apply Effect.le_trans traceBound
    apply Effect.le_trans
      (Effect.le_seq (Effect.le_refl firstTrace) secondThirdBound)
    simpa only [Effect.mul_assoc] using
      Effect.le_refl ((firstTrace * secondTrace) * thirdTrace)

theorem seq_one_left (language : EffectLanguage) :
    seq (principal 1) language = language := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  constructor
  · rintro ⟨pureTrace, rightTrace, pureBound, rightMember, traceBound⟩
    have pureEq := Effect.sublist_nil pureBound
    subst pureTrace
    exact language.downward (by simpa using traceBound) rightMember
  · intro member
    exact ⟨1, trace, Effect.le_refl 1, member, by
      simpa using Effect.le_refl trace⟩

theorem seq_one_right (language : EffectLanguage) :
    seq language (principal 1) = language := by
  apply EffectLanguage.ext
  funext trace
  apply propext
  constructor
  · rintro ⟨leftTrace, pureTrace, leftMember, pureBound, traceBound⟩
    have pureEq := Effect.sublist_nil pureBound
    subst pureTrace
    exact language.downward (by simpa using traceBound) leftMember
  · intro member
    exact ⟨trace, 1, member, Effect.le_refl 1, by
      simpa using Effect.le_refl trace⟩

/-- Finite sequential powers of a language.  `power L n` describes at most
the traces generated by exactly `n` iterations, with downward closure making
each individual iteration a may-effect bound. -/
def power (language : EffectLanguage) : Nat → EffectLanguage
  | 0 => principal 1
  | count + 1 => seq language (power language count)

@[simp] theorem power_zero (language : EffectLanguage) :
    power language 0 = principal 1 := rfl

@[simp] theorem power_succ (language : EffectLanguage) (count : Nat) :
    power language (count + 1) = seq language (power language count) := rfl

/-- Kleene closure of a may-effect language: the downward closure of all its
finite sequential powers. -/
def star (language : EffectLanguage) : EffectLanguage where
  contains trace := ∃ count, (power language count).contains trace
  downward := by
    intro smaller larger below
    rintro ⟨count, member⟩
    exact ⟨count, (power language count).downward below member⟩

theorem power_le_star (language : EffectLanguage) (count : Nat) :
    power language count ≤ star language :=
  fun _ member => ⟨count, member⟩

theorem one_le_star (language : EffectLanguage) :
    principal 1 ≤ star language := by
  simpa only [power_zero] using power_le_star language 0

/-- One further body execution is absorbed by its Kleene closure.  This is
the generic recursive-grade inequality unavailable for finite words. -/
theorem seq_star_le_star (language : EffectLanguage) :
    seq language (star language) ≤ star language := by
  rintro trace ⟨bodyTrace, tailTrace, bodyMember,
    ⟨count, tailMember⟩, traceBound⟩
  exact ⟨count + 1, ⟨bodyTrace, tailTrace, bodyMember,
    tailMember, traceBound⟩⟩

theorem power_mono (bound : lower ≤ upper) (count : Nat) :
    power lower count ≤ power upper count := by
  induction count with
  | zero => exact le_refl _
  | succ count ih => exact seq_mono bound ih

theorem star_mono (bound : lower ≤ upper) : star lower ≤ star upper := by
  rintro trace ⟨count, member⟩
  exact ⟨count, power_mono bound count trace member⟩

/-- `star body` is the least language containing the pure trace and closed
under prefixing by one body execution. -/
theorem star_le_of_prefixed
    (pureBound : principal 1 ≤ candidate)
    (stepBound : seq body candidate ≤ candidate) :
    star body ≤ candidate := by
  have powerBound : ∀ count, power body count ≤ candidate := by
    intro count
    induction count with
    | zero => exact pureBound
    | succ count ih => exact le_trans (seq_mono (le_refl body) ih) stepBound
  rintro trace ⟨count, member⟩
  exact powerBound count trace member

theorem star_least_fixed_characterization (body : EffectLanguage) :
    principal 1 ≤ star body ∧ seq body (star body) ≤ star body ∧
      ∀ candidate : EffectLanguage, principal 1 ≤ candidate →
        seq body candidate ≤ candidate → star body ≤ candidate :=
  ⟨one_le_star body, seq_star_le_star body,
    fun _ pureBound stepBound => star_le_of_prefixed pureBound stepBound⟩

end EffectLanguage
end EffectSemantics
