import EffectSemantics.Denotational.EffectLanguage

namespace EffectSemantics

open EffectLanguage

/-- The grade-theoretic obligations needed to assign `latent` to a recursive
function whose one-unfolding, nonrecursive prefix has grade `body`.

The pure inclusion accounts for zero unfoldings.  `unfoldClosed` validates
one more body execution followed by the recursive call.  `least` records that
the proposed annotation contains no behavior forced by recursion beyond these
two closure requirements. -/
structure RecursiveGradeCert (body latent : EffectLanguage) : Prop where
  pureIncluded : principal 1 ≤ latent
  unfoldClosed : seq body latent ≤ latent
  least : ∀ candidate : EffectLanguage,
    principal 1 ≤ candidate → seq body candidate ≤ candidate →
      latent ≤ candidate

/-- Kleene closure is the canonical recursive annotation for every body
language. -/
theorem starRecursiveGradeCert (body : EffectLanguage) :
    RecursiveGradeCert body (star body) where
  pureIncluded := one_le_star body
  unfoldClosed := seq_star_le_star body
  least := fun _ pureBound stepBound =>
    star_le_of_prefixed pureBound stepBound

/-- A finite effect word embeds as its principal downward-closed language. -/
def embedFiniteEffect (effect : Effect) : EffectLanguage := principal effect

theorem embedFiniteEffect_reflects_order :
    embedFiniteEffect lower ≤ embedFiniteEffect upper ↔ lower ≤ upper :=
  principal_le_principal_iff

theorem embedFiniteEffect_pure :
    embedFiniteEffect 1 = principal 1 := rfl

theorem embedFiniteEffect_seq :
    seq (embedFiniteEffect left) (embedFiniteEffect right) =
      embedFiniteEffect (left * right) :=
  principal_seq left right

/-- Every old finite typing bound remains valid after embedding. -/
theorem embedFiniteEffect_mono (bound : lower ≤ upper) :
    embedFiniteEffect lower ≤ embedFiniteEffect upper :=
  principal_mono bound

/-- Grade-level typing rule for `fix f. body; f`: after embedding the finite
body grade, its regular closure accepts one unfolding. -/
theorem finiteBody_unfolds_into_star (body : Effect) :
    seq (embedFiniteEffect body) (star (embedFiniteEffect body)) ≤
      star (embedFiniteEffect body) :=
  seq_star_le_star _

/-- The regular annotation is also the least possible language annotation
for the repeated finite body. -/
theorem finiteBody_star_least
    (pureBound : principal 1 ≤ candidate)
    (unfoldBound : seq (embedFiniteEffect body) candidate ≤ candidate) :
    star (embedFiniteEffect body) ≤ candidate :=
  star_le_of_prefixed pureBound unfoldBound

/-- The singleton-operation loop from the finite-word impossibility theorem
is typable at the language grade generated by that operation. -/
theorem operationLoop_has_recursive_grade (atom : EffectAtom) :
    RecursiveGradeCert (embedFiniteEffect [atom])
      (star (embedFiniteEffect [atom])) :=
  starRecursiveGradeCert _

/-- The obstruction/repair pair in one checked statement: no exact finite
word can close the recursive equation, while the canonical language can. -/
theorem finite_impossible_regular_possible (atom : EffectAtom) :
    (∀ effect : Effect, ¬ ([atom] * effect ≤ effect)) ∧
      seq (embedFiniteEffect [atom]) (star (embedFiniteEffect [atom])) ≤
        star (embedFiniteEffect [atom]) :=
  ⟨Effect.not_cons_le_self atom, seq_star_le_star _⟩

end EffectSemantics
